services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    ports:
      - "8070:8070"
    ulimits:
      core: 0
    init: true
    restart: unless-stopped
    healthcheck:
      disable: true

  python-app:
    build:
      context: ./python-app
    volumes:
      - ./python-app:/app
      - ./pdfs:/app/pdfs
    depends_on:
      - grobid
    environment:
      - GROBID_URL=http://grobid:8070
      - PDF_FOLDER=/app/pdfs
    # Se ejecuta primero tests.py; si finaliza con éxito, se continúa con main.py
    command: /bin/sh -c "python tests.py && python keyword_cloud_generator.py"
    restart: unless-stopped